### model
model_name_or_path: base_models/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: data/processed_llm/
dataset: MC_Scale100_Split82_InitOrd_ValueOnlySeq_Cot0_En
template: qwen
cutoff_len: 1024
max_samples: 40000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: checkpoints/cross_entropy/MC_Scale100_Split82_InitOrd_ValueOnlySeq_Cot0_Qwen2.5-7B-Instruct_Epochs5_En
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
save_total_limit: 2

### eval
val_size: 0
per_device_eval_batch_size: 1
eval_strategy: "no"
eval_steps: 500000